<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 * Define types needed by the lifecycle section of the AN Site
 * @global type $GLOBALS['an_lifecycle_types']
 * @name $an_lifecycle_types 
 */
$GLOBALS['an_community_types'] = array(
    'community' => array(
        // Content Properties
        'name' => 'Community',
        'description' => 'TBD',
        'title' => 'Community',
    ),
    'conversation' => array(
        // Content Properties
        'name' => 'Conversation',
        'description' => 'TBD',
        'title' => 'Conversation',
    ),
 
);

?>
