<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Sets up patuauto alias' for the lifecycle content types. 
 * @global type $GLOBALS['an_node_alias']
 * @name $an_node_alias 
 */
$GLOBALS['an_node_community_alias'] = array(
    'community' => 'communities/community/[node:system-title]',
    'conversation' => 'communities/conversation/[node:system-title]',
);

?>