<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

function new_resource_form_enable() {
	module_load_include('inc', 'captcha');

	// hide submitters and comments for webforms
	variable_set('node_submitted_webform', 0);
	variable_set('comment_webform', 0);

	$node = new stdClass();

	$node->type = 'webform';
	node_object_prepare($node);
	$node->title = 'Submit New Resource';
	$node->language = 'en';
	$node->comment = 0;

	node_save($node);

	// title component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'title',
		'name' => 'Title',
		'type' => 'textfield',
		'value' => "",
		'extra' => array('description' => "The resource's title."),
		'mandatory' => 1,
		'weight' => 0,
	);

	// description component
	$cid = webform_component_insert($component);

	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'description',
		'name' => 'Description',
		'type' => 'textarea',
		'value' => "",
		'extra' => array('description' => "A short description of the resource."),
		'mandatory' => 1,
		'weight' => 1,
	);

	$cid = webform_component_insert($component);

	// link component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'resource_link',
		'name' => 'Resource Link',
		'type' => 'textfield',
		'value' => "",
		'extra' => array('description' => "A link to the resource in question."),
		'mandatory' => 0,
		'weight' => 2,
	);

	$cid = webform_component_insert($component);

	// file component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'resource_file',
		'name' => 'Resource File',
		'type' => 'file',
		'value' => "",
		'extra' => array(
			'description' => "If a link is not available, you may upload a copy of the resource.",
			'filtering' => array(
				'size' => '2 MB',
				'types' => array('txt', 'rtf', 'html', 'odf', 'pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'xml'),
				'addextensions' => ''
		)),
		'mandatory' => 0,
		'weight' => 3,
	);

	$cid = webform_component_insert($component);

	// disclaimer component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'disclaimer',
		'name' => 'Disclaimer',
		'type' => 'select',
		'value' => "",
		'extra' => array(
			'items' => "affirm|For materials that are not publicly available, I own the copyright or have obtained the necessary rights/permissions for the content that I am submitting to AccrualNet.",
			'multiple' => 1),
		'mandatory' => 1,
		'weight' => 4,
	);

	$cid = webform_component_insert($component);

	captcha_set_form_id_setting("webform_client_form_$node->nid", 'recaptcha/reCAPTCHA');

	drupal_set_message("Created 'Submit New Resource' webform node at <a href='/content/submit-new-resource'>/content/submit-new-resource</a> (or <a href='/node/$node->nid'>/node/$node->nid</a> directly)");
}

function new_resource_form_disable() {

	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
			->entityCondition('bundle', 'webform')
			->propertyCondition('title', 'Submit New Resource');
	$result = $query->execute();

	if (isset($result['node'])) {
		node_delete(array_keys($result['node']));
	}
}

?>
