<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

function new_community_form_enable() {
	module_load_include('inc', 'captcha');

	$node = new stdClass();

	$title = 'Create a Community';

	$weight = 0;

	$node->type = 'webform';
	node_object_prepare($node);
	$node->title = $title;
	$node->language = 'en';
	$node->comment = 0;

	node_save($node);

	// submitter name component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'submitter',
		'name' => 'Submitter Name',
		'type' => 'textfield',
		'value' => "%username",
		'extra' => array('description' => "Your name."),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	// email component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'email',
		'name' => 'Work-Related Email',
		'type' => 'email',
		'value' => "%useremail",
		'extra' => array('description' => "Your work-related email address."),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	// title component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'name',
		'name' => 'Name of Group',
		'type' => 'textfield',
		'value' => "",
		'extra' => array('description' => "A name for the community."),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	// purpose component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'purpose',
		'name' => 'Purpose for AccrualNet Communities',
		'type' => 'textarea',
		'value' => "",
		'extra' => array('description' => "Elaborate on the pupose this group will serve in terms of the AccrualNet community."),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	// description component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'description',
		'name' => 'Description',
		'type' => 'textarea',
		'value' => "",
		'extra' => array('description' => "A short description of the group."),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	// membership component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'membership',
		'name' => 'Proposed Membership',
		'type' => 'textarea',
		'value' => "",
		'extra' => array('description' => "A description of the intended membership of this group."),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	// duration component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'duration',
		'name' => 'Group Duration',
		'type' => 'textfield',
		'value' => "",
		'extra' => array('description' => "The desired duration of the group's existence."),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	// moderator name component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'moderator',
		'name' => 'Moderator Name',
		'type' => 'textfield',
		'value' => "",
		'extra' => array('description' => "The moderator's name, if different from the submitter."),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	// moderator's email component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'moderator_email',
		'name' => "Moderator's Work-Related Email",
		'type' => 'email',
		'value' => "",
		'extra' => array('description' => "The moderator's work-related email address."),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	// disclaimer component
	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'guideline_agreement',
		'name' => '',
		'type' => 'select',
		'value' => "",
		'extra' => array(
			'items' => "affirm|I agree to adhere to NCI website and community of practice guidelines, and to provide periodic feedback to NCI on the group.",
			'multiple' => 1),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	$component = array(
		'nid' => $node->nid,
		'pid' => 0,
		'form_key' => 'contribute_agreement',
		'name' => '',
		'type' => 'select',
		'value' => "",
		'extra' => array(
			'items' => "affirm|I agree to support and contribute to the public site in general.",
			'multiple' => 1),
		'mandatory' => 1,
		'weight' => $weight++
	);

	$cid = webform_component_insert($component);

	captcha_set_form_id_setting("webform_client_form_$node->nid", 'recaptcha/reCAPTCHA');

	drupal_set_message("Created 'Create a Community' webform node at <a href='/content/create-community'>/content/create-community</a> (or <a href='/node/$node->nid'>/node/$node->nid</a> directly)");
}

function new_community_form_disable() {
	/* $query = new EntityFieldQuery();
	  $query->entityCondition('entity_type', 'node')
	  ->entityCondition('bundle', 'webform')
	  ->propertyCondition('title', 'Create a Community');
	  $result = $query->execute();

	  if (isset($result['node'])) {
	  node_delete(array_keys($result['node']));
	  } */
}

function new_community_form_form_alter(&$form, &$form_state, $form_id) {
	if (!isset($form['#node'])
			|| $form['#node']->type != 'webform'
			|| $form['#node']->title != 'Create a Community'
			|| !isset($form['submitted']))
		return;

	$form['submitted']['purpose']['#description'] = "Tell us how this group will benefit by using an AccrualNet&trade; Community of Practice.";
	$form['submitted']['description']['#description'] = "Please write a brief description of your group.  This description will appear on the AccrualNet&trade; Communities of Practice page.";
	$form['submitted']['membership']['#description'] = "Tell us who can join your group.  Anyone?  A certain type of professional? Or people with a certain interest?  Or only members of an existing group?";
	$form['submitted']['moderator']['#required'] = true;
	$form['submitted']['moderator_organization']['#required'] = true;
	$form['submitted']['moderator_email']['#required'] = true;
	$form['submitted']['moderator_phone']['#required'] = true;
}

?>
