<?php

function communities_node_info() {
    return array(
        'community2' => array(
            'name' => t('Community2'),
            'base' => 'node_content',
            'description' => t('Community (Group)'),
            'has_title' => TRUE,
            'title_label' => 'Group Name',
        // 'custom' => TRUE, // Add this line in when debugging
        )
    );
}

function communities_enable() {
    node_types_rebuild();
    $types = node_type_get_types();
    //node_add_body_field($types['community2']);
    $content_type = node_type_set_defaults($types['community2']);
//We add a body field and set the body label immediately.
    node_add_body_field($content_type, 'Group Description');
// Save the content type
    node_type_save($content_type);


// Create all the fields we are adding to our content type.
// http://api.drupal.org/api/function/field_create_field/7
    foreach (_communities_installed_fields() as $field) {
        field_create_field($field);
    }
// Create all the instances for our fields.
// http://api.drupal.org/api/function/field_create_instance/7
    foreach (_communities_installed_instances() as $instance) {
        $instance['entity_type'] = 'node';
        $instance['bundle'] = 'community2';
        field_create_instance($instance);
    }
}

function communities_disable() {
    drupal_set_message($message = 'Communities being disabled. Right now, content not deleted, but type and fields are.');

    foreach (array_keys(_communities_installed_fields()) as $field) {
        field_delete_field($field);
    }
// Loop over any remaining field instances attached to the communities
// content type (such as the body field) and delete them individually.
// http://api.drupal.org/api/function/field_delete_field/7
    $instances = field_info_instances('node', 'community2');
    foreach ($instances as $instance_name => $instance) {
        field_delete_instance($instance);
    }
// Delete our content type
// http://api.drupal.org/api/function/node_type_delete/7
    node_type_delete('community2');
// Purge all field infromation
// http://api.drupal.org/api/function/field_purge_batch/7
    field_purge_batch(1000);
}

function _communities_installed_fields() {
    $t = get_t();
    return array(
    /* 'communities_color' => array(
      'field_name' => 'communities_color',
      'cardinality' => 3,
      'type' => 'text',
      'settings' => array(
      'max_length' => 60,
      ),
      ),
      'communities_quantity' => array(
      'field_name' => 'communities_quantity',
      'cardinality' => 1,
      'type' => 'text',
      ), */
    );
}

function _communities_installed_instances() {
    $t = get_t();
    return array(
        /* 'communities_color' => array(
          'field_name' => 'communities_color',
          'label' => $t('The colors available for this object.'),
          'widget' => array(
          'type' => 'text_textfield',
          ),
          'display' => array(
          'example_node_list' => array(
          'label' => 'hidden',
          'type' => 'communities_colors',
          ),
          ),
          ),
          'communities_quantity' => array(
          'field_name' => 'communities_quantity',
          'label' => $t('Quantity required'),
          'type' => 'text',
          'widget' => array(
          'type' => 'text_textfield',
          ),
          'display' => array(
          'example_node_list' => array(
          'label' => 'hidden',
          'type' => 'hidden',
          ),
          ),
          ), */
        'group_group' => array(
            'field_name' => OG_GROUP_FIELD,
            'label' => $t('Group'),
            'type' => 'list_boolean',
            'widget' => array(
                'module' => 'options',
                'settings' => array(),
                'type' => 'options_onoff',
                'weight' => -1,
            ),
            'default_value' => array(0 => array('value' => 1)), // Very important the default is true because we'll be hiding this in the create form
            'display' => array(// For some reason this part doesn't work. No idea why!
                'default' => array(
                    'label' => 'hidden',
                    'type' => 'hidden',
                ),
                'full' => array(
                    'label' => 'hidden',
                    'type' => 'hidden'
                ),
                'teaser' => array(
                    'label' => 'hidden',
                    'type' => 'hidden'
                ),
            ),
        ),
    );
}

function communities_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'community2_node_form') {

        // Do not automatically publish
        $form['options']['status']['#default_value'] = FALSE;

        // Do not promote to front page
        $form['options']['promote']['#default_value'] = FALSE;

        // Don't allow Preview
        $form['actions']['preview']['#access'] = FALSE;
    }

    return $form;
}

function communities_theme($existing, $type, $theme, $path) {

    return array(
        'community2_node_form' => array(
            'arguments' => array('form' => null),
            'path' => $path,
            'template' => 'community--node-form', //name of your template file, it can be anything
            'render element' => 'form'
        )
    );

    return $items;
}

?>