<?php

/* Created By: John Doyle
 * Created On: June 11, 2012
 * Last Updated By: Lauren
 * Last Updated On: July 9, 2012
 *
 */

//Load the an lifecycles globals.
module_load_include('inc', 'an_lifecycle',' lifecycle.globals');

function an_education_pages_menu() {
  $items['education'] = array(
    'title' => 'Education & Training',
    'page callback' => 'education_landing_page',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'education_landing_page.pages.inc',
  );
  $items['education/%'] = array (
    //'title' => 'Resources and Tools Level 2',
    'page callback' => 'education_level_2_page',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'education_level_2.pages.inc',
  );

  return $items;
}