<?php

/* Created By: John Doyle
 * Created On: June 11, 2012
 * Last Updated By: Doyle
 * Last Updated On: June 11, 2012
 *
 */

/**
 *
 * @param <type> $role_name
 */
function _nci_roles_and_permissions_create_roles($role_name) {
	$role = user_role_load_by_name($role_name);

	if (!$role) {
		$role = new stdClass();
		$role->name = $role_name;
		user_role_save($role);
	} else {

		watchdog('nci_roles_and_permissions', 'The role %role_name is set',
				array('%role_name' => $role_name), WATCHDOG_ERROR);
	}
}

/**
 *
 * @param <type> $role_name
 * @param <type> $role_permissions 
 */
function _nci_roles_and_permissions_update_perms($role_name, $role_permissions) {

	$role = user_role_load_by_name($role_name);
	//Make sure the role exists. user_role_load_by_name
	//will return false if it doesnt exist.
	if ($role) {
		$role_rid = $role->rid;
		$permissions = user_permission_get_modules();
		$missing = array();
		foreach ($role_permissions as $permission => $value) {
			if (!isset($permissions[$permission])) {
				$missing[] = $permission;
				unset($role_permissions[$permission]);
			}
		}

		if (!empty($missing)) {
			$message = "Unknown permissions for $role_name: ";
			$message .= implode(", ", $missing);
			drupal_set_message($message);
		}

		user_role_change_permissions($role_rid, $role_permissions);
	} else {
		watchdog('nci_roles_and_permissions', 'The role %role_name does not exist',
				array('%role_name' => $role_name), WATCHDOG_ERROR);
	}
}

