<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *Provides the navigation structure for the lifecycle section of the AN site.
 * @global type $GLOBALS['an_stage_strategy']
 * @name $an_stage_strategy 
 */
$GLOBALS['an_stage_strategy'] = array(
    'Developing a Trial' => array(
        'Strategy1',
        'Strategy2',
        'Strategy3',
        'Strategy4'
        ),
    'Selecting & Preparing to Open the Trial' => array(
        'Strategy1',
        'Strategy2',
        'Strategy3',
        'Strategy4'
        ),
    'Recruiting & Communicating with Participants' => array(
        'Strategy1',
        'Strategy2',
        'Strategy3',
        'Strategy4'
        ),
    'Implementing the  Trial' => array(
        'Strategy1',
        'Strategy2',
        'Strategy3',
        'Strategy4'
        ),
    'Evaluating Accrual & Lessons Learned' => array(
        'Strategy1',
        'Strategy2',
        'Strategy3',
        'Strategy4'
        ),
    );


?>
