<?php
/* * ***
 * Created By: Lauren
 * Created On: June 27, 2012
 *
 * Last Updated By: Lauren
 * Last Updated On: June 29, 2012
 * *** */

// All of the Resource Types
$GLOBALS['an_lifecycle_types'] = array(
    'lifecycle_stage' => array(
        // Content Properties
        'name' => 'Lifecycle Stage',
        'description' => 'TBD',
        'title' => 'Stage Name',
    ),
    'lifecycle_strategy' => array(
        // Content Properties
        'name' => 'Lifecycle Strategy',
        'description' => 'TBD',
        'title' => 'Strategy Name',
    ),
    
);
?>
