<?php

/* Created By: John Doyle
 * Created On: June 11, 2012
 * Last Updated By: Lauren
 * Last Updated On: July 9, 2012
 *
 */

//Load the an lifecycles globals.
module_load_include('inc', 'an_lifecycle', ' lifecycle.globals');
//add resource types global.
module_load_include('inc', 'resource', 'types');

function an_reports_menu() {
	$items['admin/reports/accrualnet'] = array(
		'title' => 'AccrualNet Reports',
		'description' => 'A variety of reports specific to the AccrualNet site.',
		'page callback' => 'reports_landing_page',
		'access arguments' => array('access content'),
		'type' => MENU_SUGGESTED_ITEM,
		'file' => 'reports_landing_page.pages.inc',
		'hidden' => 0,
	);
	$items['admin/reports/accrualnet/%'] = array(
		//'title' => 'Resources and Tools Level 2',
		'page callback' => 'reports_level_2_page',
		'access arguments' => array('access content'),
		'page arguments' => array(3),
		'type' => MENU_SUGGESTED_ITEM,
		'file' => 'reports_level_2.pages.inc',
		'hidden' => 0,
	);
	$items['admin/reports/accrualnet/%/export'] = array(
		//'title' => 'Resources and Tools Level 2',
		'page callback' => 'reports_level_2_export',
		'access arguments' => array('access content'),
		'page arguments' => array(3),
		'type' => MENU_SUGGESTED_ITEM,
		'file' => 'reports_level_2.pages.inc',
		'hidden' => 1,
	);

	return $items;
}

function an_reports_menu_link_alter(&$item) {
	// force reports links to visible
	if (strpos($item['link_path'], 'admin/reports/accrualnet') === 0) {
		$item['hidden'] = 0;
	}
}

function an_reports_menu_alter(&$items) {
	if (is_array($items)) {
		foreach ($items as $item) {
			if (isset($item['link_path']) && strpos($item['link_path'], 'admin/reports/accrualnet') === 0) {
				$item['hidden'] = 0;
			}
		}
	}
}

?>