<?php
/* * ***
 * Created By: Doyle
 * Created On: July 1, 2012
 *
 * Last Updated By: Doyle
 * Last Updated On: July 12, 2012
 * *** */


/**
 * Define types needed by the lifecycle section of the AN Site
 * @global type $GLOBALS['an_lifecycle_types']
 * @name $an_lifecycle_types 
 */
$GLOBALS['homepage_content_types'] = array(
    'homepage' => array(
        // Content Properties
        'name' => 'Homepage',
        'description' => 'TBD',
        'title' => 'Homepage',
    ),

);
?>
