<?php
/* * ***
 * Created By: Lauren
 * Created On: July 26, 2012
 *
 * Last Updated By: Lauren
 * Last Updated On: July 26, 2012
 * *** */

$GLOBALS['an_communities_field_topic_options'] = array(
    'announcements' => 'Announcements',
    'general' => 'General Topics',
    'patient_related_issues' => 'Patient-Related Issues',
    'provider_related_issues' => 'Provider-Related Issues',
    'study_issues' => 'Study Issues',
    'system_issues' => 'Systems and Regulatory Issues',
    'ethical_issues' => 'Ethical Issues',
    'journal_club' => 'Journal Club',
    'all_conversations' => 'All Conversations',
    'communities_of_practice' => 'Communities of Practice'
);
?>