<?php
/* * ***
 * Created By: Lauren
 * Created On: July 26, 2012
 *
 * Last Updated By: Lauren
 * Last Updated On: July 26, 2012
 * *** */

$GLOBALS['an_communities_field_topic_options'] = array(
    'announcements' => 'Announcements',
    'general' => 'General Topics',
    'patient_related_issues' => 'Patient-Related Issues',
    'provider_related_issues' => 'Provider-Related Issues',
    'system_issues' => 'Systems and Regulatory Issues',
    'study_issues' => 'Study Issues',
    'ethical_issues' => 'Ethical Issues',
    'journal_club' => 'Journal Club',
);

$GLOBALS['an_communities_field_topic_descriptions'] = array(
    'announcements' => 'Check out this area for announcements about AccrualNet™ from the AccrualNet™ Team. Or feel free to post announcements here that are relevant to the entire AccrualNet™ community.',
    'general' => "Not every topic is easy to categorize!  Start conversations here about general topics related to clinical trial accrual.",
    'patient_related_issues' => "Understanding the perspective and needs of the research participant, such as cost and insurance issues, logistics and transportation concerns, and language and cultural beliefs, is key to planning and running a successful trial.  In this section, pose a question or join an ongoing conversation around these important topics.  Or to learn more about Patient-Related Issues, <a href='/literature/patient_related'>click here</a>.",
    'provider_related_issues' => "The provider’s awareness of, attitudes about and experience with clinical trials are important factors that can make or break a study.  In this section, read about issues that your colleagues have encountered, such as incentives and relationships with participants, or contribute your experience by joining a conversation.  Or to learn more about Provider-Related Issues, <a href='/literature/provider_related'>click here</a>.",
    'study_issues' => "Ensuring that protocols are written in a way that minimizes burden to both participants and staff is critical.  Use the conversations here to find new approaches, seek solutions and share your insights for issues such as eligibility requirements, randomization or placebo usage. Or to learn more about Study Issues, <a href='/literature/study'>click here</a>.",
    'system_issues' => "The impact of systems and regulatory issues, like insurance coverage and inadequate staffing, on clinical trial accrual cannot be overlooked. Here’s the place to discover best practices, talk about resources and engage with other clinical trial professionals.  Or to learn more about Systems and Regulatory Issues, <a href='/literature/systems_and_regulatory'>click here</a>.",
    'ethical_issues' => "Basic moral principles and patient’s rights are always top of mind in planning and conducting clinical trials.  Browse the conversations in this area to find information about ethical issues such as conflict of interest, and informed consent.  Or to learn more about Ethical Issues, <a href='/literature/ethical'>click here</a>.",
    'journal_club' => "Coming in 2013!  A journal club just for AccrualNet™ members focused on issues that you tell us are important! Post a conversation here to give us your ideas—topics, speakers, articles, formats. You tell us!",
);
?>