<?php
/* * ***
 * Created By: Doyle
 * Created On: July 1, 2012
 *
 * Last Updated By: Doyle
 * Last Updated On: July 12, 2012
 * *** */


/**
 * Define types needed by the lifecycle section of the AN Site
 * @global type $GLOBALS['an_lifecycle_types']
 * @name $an_lifecycle_types 
 */
$GLOBALS['featured_content_types'] = array(
    'dynamic_content_block' => array(
        // Content Properties
        'name' => 'Dynamic Content Block',
        'description' => 'TBD',
        'title' => 'Dynamic Content Block',
    ),
    'content_block' => array(
        // Content Properties
        'name' => 'Manual Content Block',
        'description' => 'TBD',
        'title' => 'Manual Content Block',
    ),
    'featured_content_carousel' => array(
        // Content Properties
        'name' => 'Featured Content Carousel',
        'description' => 'TBD',
        'title' => 'Featured Content Carousel',
    ),
    
);
?>
