<?php

/**
 * @file
 * A module that customizes various uer features for NCI sites.
 */
function nci_custom_user_form_user_register_form_alter(&$form, &$form_state) {
	//dpm($form, '$form');
	//dpm($form_state, '$form_state');

	$form['picture']['#access'] = TRUE;
	$form['picture']['#title'] = '';
	$form['picture']['picture_upload']['#description'] .= ' This photo will be viewable by all registered users if you choose to participate in conversations or comment on resources.';
	$form['picture']['#weight'] = 5;
	$form['account']['mail']['#title'] = 'Work-related Email';
}

/*function nci_custom_user_form_alter(&$form, &$form_state, $form_id) {
	print dpm($form_id, '$form_id');

	/* if($form_id == 'field_ui_field_settings_form'){
	  $form['field']['settings']['allowed_values_function'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Allowed value function'),
	  '#default_value' => $form['field']['settings']['allowed_values']['#field']['allowed_values_function']
	  );
	  } 
}*/

?>
